---
- name: ensure docker group exists
  group:
    name: docker

- name: add my user to docker group
  user:
    name: davido
    groups: docker
    append: yes

- name: start docker service
  ansible.builtin.service:
    name: docker
    enabled: yes
    state: started

- name: start containerd service
  ansible.builtin.service:
    name: containerd
    enabled: yes
    state: started

#- name: dns fix firewall rule
#  ansible.posix.firewalld:
#    interface: docker0
#    permanent: yes
#    immediate: yes
#    zone: trusted
#    state: enabled
