---
- name: make .ssh folder
  ansible.builtin.file:
    path: ~/.ssh
    state: directory

- name: create keypair
  community.crypto.openssh_keypair:
    path: ~/.ssh/id_rsa
    type: rsa
    size: 4096
    comment: "{{ ansible_facts['nodename'] }}"
